# Basic
title: Peter's Den
subtitle: <span style="font-size:12px">悲观者只见到机会后面的问题，乐观者却看见问题后面的机会</span>
description: Hello，在下2012年涉足Apple Developer，至今在iOS/OSX领域混迹多年，本职工作以iOS为主
welcome_message: 精通Objective-c/Swift，对Python/Java/.Net/JavaScript也略懂一二，会与大家在这里记录分享
# creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blogs
    description: 访问Peter's all blogs

# Navigation buttons in the front page.
nav:
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: peter
    # duoshuo: 
    
# Social
social:
    # weibo: onevcat
    github: jxbsir
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: i@jxb.name

# Google Analytics
ga:
    id: UA-72007485-5
    host: jinxuebin.cn
